export const FETCH_JOB_START = 'FETCH_JOB_START'
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS'
export const FETCH_JOB_FAIL = 'FETCH_JOB_FAIL'
export const SET_VIEW_JOB_DETAILS = "SET_VIEWJOB_DETAILS"